version: "3"

services:
  discoveryservice:
    image: "com.kramkroc/discovery-service"
    hostname: discoveryservice
    ports:
      - "8761:8761"
    networks:
      - demo-network
    deploy:
      restart_policy:
        condition: any    

  configserver:
    image: "com.kramkroc/config-server"
    hostname: configserver
    restart: always  
    depends_on:
      - discoveryservice
    environment:
       EUREKA_HOST: discoveryservice
       EUREKA_PORT: 8761
    ports:
      - "8888:8888"
    networks:
      - demo-network
    deploy:
      restart_policy:
        condition: any      

  sampleservice:
    image: "com.kramkroc/sample-service"
    hostname: sampleservice
    restart: always
    depends_on:
      - discoveryservice
      - configserver
    environment:
       EUREKA_HOST: discoveryservice
       EUREKA_PORT: 8761
    ports:
      - "8082:8082"
    networks:
      - demo-network      
    deploy:
      restart_policy:
        condition: any
        
networks:
  demo-network:
    external: true
